### ISSUE TITLE
LSF exit code mapping

### ISSUE THREAD

**Issue by asm582** [IBMSpectrumComputing/lsf-kubernetes#4] opened 2020-06-15 17:18 UTC
Hello,
Not sure if this is the correct repo to open issue, if not please close this issue and I can reopen the issue to a desired one.
Can you please share details on LSF exit code mapping, for instance, exit code 32 to UNIX signal mapping. The documentation for 32 code says EXIT but there could be several reasons for exit. Does exit code 32 mean SIGPROF?
 Thanks

**Comment by adamsla** [comment] 2020-06-15 17:27
This is old, but continue to be relevant.

[Error Status Reporting in LSF and RTM.pptx](https://github.com/IBMSpectrumComputing/lsf-kubernetes/files/4781910/Error.Status.Reporting.in.LSF.and.RTM.pptx)

**Comment by adamsla** [comment] 2020-06-15 17:29
In RTM we provide a custom column that will provide the App: XX, Sig: XX, or something like what can be seen in the image below.

![image](https://user-images.githubusercontent.com/30323347/84687725-2d23a300-af0c-11ea-9a83-77c30a1f0ffe.png)

**Comment by adamsla** [comment] 2020-06-15 17:29
Real old screen shot too.

**Comment by asm582** [comment] 2020-06-15 17:35
@adamsla Really informative. I still don't see the exit code 32 mapping.

**Comment by adamsla** [comment] 2020-06-15 18:26
@asm582, there are some cases where the raw exit code slips past and for that, I'm not quite certain how it happens (not the LSF developer, RTM yes, LSF no).  I think this may happen when you get a post exec error, though I've never confirmed.  

If you are getting an "exit status" 32, that would likely be the raw signal.  But let's be clear we are talking about the same thing.  If you run either a 'bjobs -l' or a 'bhist -l jobid', you should get either the real "exit code" (as exited by the application), or something like "TERM_OWNER".

Now, as said, bhist and bjobs will give the real exit code, instead of the various API's which will give you the three column crazy combo (the construction of the value is a Linux design limitation).  I hope that makes more sense.

**Comment by asm582** [comment] 2020-06-15 19:15
@adamsla Thanks for explaining. I am looking at lsf.acct files in the cluster and I see a lot of exit codes with 32.

**Comment by adamsla** [comment] 2020-06-15 20:03
If you are looking at the raw account files and it's 'exitStatus' from the API perspective, then a 32 is likely a signal/post exec failure.  Try 'bacct -l jobid', and see what it comes back with.

**Comment by adamsla** [comment] 2020-06-15 20:04
Do a bhist -l jobid and see what that comes back with.

**Comment by SMark-Black** [comment] 2022-06-17 14:27
Closing this as it seems to be resolved.

**Closed as completed by SMark-Black** 2022-06-17 14:27 UTC
